"use client";

// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import useAuthStore from "./Context/authStore";
import { useEffect } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initializeAuthListener = useAuthStore(
    (state) => state.initializeAuthListener
  );

  useEffect(() => {
    console.log("useEffect on layout.tsx start");
    const unsubscribe = initializeAuthListener();

    return () => {
      unsubscribe();
      console.log("useEffect on layout.tsx ends");
    };
  }, [initializeAuthListener]);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
