"use client";

// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar";
import { CoupleProvider } from "./Context/Couple-modified";
import { usePathname } from "next/navigation";
import useAuthStore from "./Context/authStore";
import { useEffect } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathName: string = usePathname();
  const noNav: string[] = [
    "/Test",
    "/Auth/Login",
    "/Auth/Signup",
    "/Auth/Confirm-email",
    "/Auth/sentVerification",
    "/Auth/setProfile",
  ];
  const initializeAuthListener = useAuthStore((state) => state.initializeAuthListener);
  useEffect(()=>{
    const unsubscribe = initializeAuthListener()
    
    return () => unsubscribe()
  }),[]

  const showNav: boolean = !noNav.includes(pathName);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          {children}
      </body>
    </html>
  );
}
